services:
  - type: web
    name: retail-logistics-core
    env: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn mywork.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.7"
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_db
          property: connectionString
      - key: SHODAN_API_KEY
        sync: false
      - key: SHODAN_QUERY
        value: "ssl.cert.expired:true"
      - key: SHODAN_RESULTS_LIMIT
        value: "10"
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: "llama-3.3-70b-versatile"
    envVarDefaults:
      DEBUG: "False"
databases:
  - name: postgres_db
    databaseName: retail_db
    user: postgres
    ipAllowList: []
