# Generated by Django 5.1.4 on 2026-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_chatconversation_chatmessage_delete_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fraud_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='comment',
            name='fraud_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('published', 'Published'), ('pending_review', 'Pending Review'), ('hidden', 'Hidden')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='fraud_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='fraud_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('published', 'Published'), ('pending_review', 'Pending Review'), ('hidden', 'Hidden')], default='published', max_length=20),
        ),
    ]
