# Generated by Django 5.1.4 on 2026-09-16 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_comment_fraud_flags_comment_fraud_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='fraud_flags',
            field=models.JSONField(blank=True, default=list, help_text='List of fraud signals detected for this comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='fraud_score',
            field=models.FloatField(default=0.0, help_text='Automated fraud risk score (0.0–1.0)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('published', 'Published'), ('hidden', 'Hidden')], default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='fraud_flags',
            field=models.JSONField(blank=True, default=list, help_text='List of fraud signals detected for this review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='fraud_score',
            field=models.FloatField(default=0.0, help_text='Automated fraud risk score (0.0–1.0)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='moderation_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('published', 'Published'), ('hidden', 'Hidden')], default='pending_review', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('top_up', 'Top Up'), ('spend', 'Spend'), ('refund', 'Refund'), ('reward', 'Reward')], max_length=20),
        ),
        migrations.CreateModel(
            name='LoginRewardStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_claimed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='login_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
